### ISSUE TITLE
ssh: Could not resolve hostname

### ISSUE THREAD

**Issue by kdmayer** [eboigne/jupyter_ssh_tunnel#1]
When executing the following step on my local machine:
    
    In another local shell (not on cluster), run the bash line output by the above script. It reads something like:
    
    ssh -N -L port:node:port user@cluster

I receive the following error. Any chance you have seen this before? 

  ssh: Could not resolve hostname sh03-12n14.int: nodename nor servname provided, or not known

**Comment by eboigne** [comment]
The `$HOSTNAME` environment variable on compute nodes on Sherlock isn't set to what would work with this script. Simply replace `ssh -N -L port:node:port user@cluster` with `ssh -N -L port:node:port user@sherlock.stanford.edu`.

For a more permanent fix: replace the line `cluster=$HOSTNAME` with `cluster="sherlock.stanford.edu"` in the remote_jupyter_notebook.sh file, or look for an environment variable that gives the address of a login node, not a compute node (`printenv`).

**Comment by kdmayer** [comment]
Perfect, works like a charm.

Merci!
